# discovery-service-prod.yml (production profile)
eureka:
  instance:
    hostname: prod.example.com
  server:
    enable-self-preservation: true

spring:
  security:
    user:
      name: ${EUREKA_USER}
      password: ${EUREKA_PASSWORD}