# development profile
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
    
spring:
  security:
    user:
      name: eurekaDevUser
      password: eurekaDevPassword