# gateway-service.yml (default config for gateway service)
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaUser:eurekaPassword@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true