server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: refresh,health, info # Add refresh here
#debug: true

logging:
  level:
#    root: DEBUG
    org.springframework.cloud: DEBUG