#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
#    enable-self-preservation: false
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eurekaLocalUser:eurekaLocalPassword@localhost:8761/eureka