server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dangersvn/springcloud-sandbox
          search-paths: 
            - config-repo # config-repository, this is a folder in our git repository
            - config-repo/{application}
          default-label: main
  security:
    user:
      name: configUser
      password: configPassword

management:
  endpoints:
    web:
      exposure:
        include: "*"