# config-service/src/main/resources/application-local.yml
server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///home/dang/workspaces/learn/microservices/config-repo # Your local config-repo location
          search-paths: 
            - config-repo
            - config-repo/{application}
          default-label: main
  security:
    user:
      name: configLocalUser
      password: configLocalPassword

management:
  endpoints:
    web:
      exposure:
        include: "*"